version: "3"
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel.prod
    ports:
        - 8000:80
    depends_on:
        - db
  db:
      container_name: db
      image: mysql:latest
      ports: 
          - 3306:3306
      environment:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      volumes:
            # - mysql_data:/var/lib/mysql
          - ./data:/var/lib/mysql # Podemos acceder al FS de mysql
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: [db]
        ports: [8080:80]

       
