version: '3'
services:
  frontend:
    image: httpd:2.4
    ports:
      - 1234:80
    networks:
      - proyecto
    volumes:
      - ./frontEnd:/usr/local/apache2/htdocs/
  
  backend:
    build: ./backend
    ports:
      - 1235:80
    networks:
      - proyecto
      
  db:
    image: mysql:latest 
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
    
    ports:
      - 3306:3306
    volumes:
       - ./db:/docker-entrypoint-initdb.d

    networks:
      - proyecto

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1237:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - proyecto
    depends_on:
      - db

networks:
  proyecto:
    driver: bridge
