FROM php:8.1-fpm
RUN mkdir -p /var/www/html/
RUN apt-get update -y && apt-get install -y \
    openssl \
    git \
    unzip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_mysql
WORKDIR /var/www/html
COPY . .
RUN composer install
EXPOSE 80

CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]

